version: "2.1"
services:

  autoencoder-env:
    build:
      context: ./image
    runtime: nvidia
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - JUPYTER_TOKEN=easy
    entrypoint: /run-jupyter
    #entrypoint: /sbin/init
    ports:
      - 8888:8888
